/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.26.                      *
*        Compiled Aug  8 2014, 14:49:30                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: SYZ                                                   *
* Dimensions:  45 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmSYZ;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsSYZ[] = {
  0x000000, 0xFFFFFF
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalSYZ = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acSYZ[] = {
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, _______X, XX______, ________, ________,
  ________, ________, ___XXXXX, XXX_____, ________, ________,
  ________, ________, _XXXXXXX, XXXX____, ________, ________,
  ________, ________, XXXXXXXX, XXXXX___, ________, ________,
  ________, _______X, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ______XX, ____XXXX, XX_____X, ________, ________,
  ________, _____XXX, XXXX__XX, X__XXXXX, X_______, ________,
  ________, _____XXX, XX_XXXXX, XXX_XXXX, X_______, ________,
  ________, _____XXX, _X__XXXX, XXX_X__X, X_______, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, _____XXX, XXXXX__X, _XXXXXXX, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, _______X, XXX_____, ___XXXX_, ________, ________,
  ________, _______X, XXXXXXXX, __XXXX__, ________, ________,
  ________, ________, XXXXXXXX, XXXXX___, ________, ________,
  ________, ________, _XXXXXXX, XXXX____, ________, ________,
  ________, ________, _X_XXXXX, XXX_____, ________, ________,
  ________, ________, _XXXXXXX, X___XX__, ________, ________,
  ________, ________, _XXXXXX_, __XXXX__, ________, ________,
  ________, ________, _XXXXXXX, XXXXXX__, ________, ________,
  ________, ________, _XXXXXXX, XXXXXX__, ________, ________,
  ________, ________, _XXXXXXX, XXXXX___, ________, ________,
  ________, X_______, _XXXXXXX, XXXXX___, ______X_, ________,
  ______XX, X_______, XXXXXXXX, XXXXX___, _______X, X_______,
  ____XXXX, ________, XXXXXXXX, XXXXXX__, _______X, XX______,
  __XXXXXX, ________, XXXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXX_, ________, _XXXXXXX, XXXXX___, _______X, XXXXX___,
  XXXXXXX_, ________, _XXXXXXX, XXXX____, _______X, XXXXX___,
  XXXXXX__, ________, _XXXXXXX, XXXX____, _______X, XXXXX___,
  XXXXXX__, ______XX, XXXXXXXX, XXXXXXX_, _______X, XXXXX___,
  XXXXXXXX, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX____X, XXXX____,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_X__X, XXXX____,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_X_X_X_, XXXX____
};

GUI_CONST_STORAGE GUI_BITMAP bmSYZ = {
  45, // xSize
  64, // ySize
  6, // BytesPerLine
  1, // BitsPerPixel
  _acSYZ,  // Pointer to picture data (indices)
  &_PalSYZ   // Pointer to palette
};

/*************************** End of file ****************************/
