/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.26.                      *
*        Compiled Aug  8 2014, 14:49:30                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: WXY                                                   *
* Dimensions:  47 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmWXY;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsWXY[] = {
  0x000000, 0xFFFFFF
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalWXY = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acWXY[] = {
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________,
  ________, ________, ____XXXX, XX______, ________, ________,
  ________, ________, ___XXXXX, XXXXX___, ________, ________,
  ________, ________, _XXXXXXX, XXXXXX__, ________, ________,
  ________, ________, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ________, _XXXXXXX, XXXXXX_X, XX______, ________,
  ________, ________, ____XXXX, XXX_____, _X______, ________,
  ________, _______X, XX___XXX, XX__XXXX, X_X_____, ________,
  ________, ________, _____XXX, XXXX__XX, XXX_____, ________,
  ________, ________, _____XXX, XXX_____, _XX_____, ________,
  ________, _____X__, _____XXX, XX______, XXX_____, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, ______XX, XXXXX___, __XXXXXX, XX______, ________,
  ________, _______X, XXXXXXX_, XXXXXXXX, XX______, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, _______X, XXXXX___, ___XXXXX, X_______, ________,
  ________, ________, XXXX____, ____XXXX, X_______, ________,
  ________, ________, XXXXX___, ___XXXXX, ________, ________,
  ________, ________, _XXXXXX_, _XXXXXXX, ________, ________,
  ________, ________, _XXXXXXX, XXXXXXX_, ________, ________,
  ________, ________, __XXXXXX, XXXXXX__, ________, ________,
  ________, ________, ___XXXXX, XXXXXXX_, ________, ________,
  ________, ________, __XXXXXX, XXXXXXX_, ________, ________,
  ________, ________, X_XXXXXX, XXXXXXX_, X_______, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ____X_XX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, XX__X_XX, XXXXXXXX, XXXXXXXX, XXX____X, X_______,
  _____XXX, XX__X_XX, XXXXXXXX, XXXXXXXX, XXX____X, XXX_____,
  ___XXXXX, XX__X_XX, XXXXXXXX, XXXXXXXX, XXX____X, XXXXXXX_,
  XXXXXXXX, XX____XX, XXXXXXXX, XXXXXXXX, XXX____X, XXXXXXX_,
  XXXXXXXX, XX___X_X, XXXXXXXX, XXXXXXXX, XX_____X, XXXXXXX_,
  XXXXXXXX, XX___X_X, XXXXXXX_, ___XXXXX, XX_X___X, XXXXXXX_,
  XXXXXXXX, XXX__X_X, XXXXXX__, ____XXXX, XX_X___X, XXXXXXX_,
  XXXXXXXX, XXX__X_X, XXXXX___, _____XXX, XX_X__XX, XXXXXXX_,
  XXXXXXXX, XXX___X_, XXXXX___, ____XXXX, XX_X__XX, XXXXXXX_,
  XXXXXXXX, XXX___X_, XXXXXX__, ___XXXXX, X_____XX, XXXXXXX_,
  XXXXXXXX, XXXX__X_, XXXXXXX_, __XXXXXX, X_X___XX, XXXXXXX_,
  XXXXXXXX, XXXX___X, _XXXXXX_, __XXXXXX, X_X__XXX, XXXXXXX_,
  XXXXXXXX, XXXXX__X, _XXXXXX_, __XXXXXX, X_X__XXX, XXXXXXX_
};

GUI_CONST_STORAGE GUI_BITMAP bmWXY = {
  47, // xSize
  64, // ySize
  6, // BytesPerLine
  1, // BitsPerPixel
  _acWXY,  // Pointer to picture data (indices)
  &_PalWXY   // Pointer to palette
};

/*************************** End of file ****************************/
